kind: workerService
version: udx.io/worker-v1/service
services:
  - name: "sshd"
    ignore: "false"
    command: "/usr/local/sbin/sshd -D -f /etc/ssh/sshd_config -e"
    autostart: "true"
    autorestart: "true"
    envs:
      - "NODE_ENV=production"

  - name: "rabbit-ssh-server"
    ignore: "false"
    command: "node /opt/sources/rabbitci/rabbit-ssh/bin/server.js"
    autostart: "true"
    autorestart: "true"
    envs:
      - "NODE_ENV=production"

  - name: "firebase-consume"
    ignore: "true"
    command: "node /opt/sources/rabbitci/rabbit-ssh/bin/firebase.consume.js"
    autostart: "true"
    autorestart: "true"
    envs:
      - "NODE_ENV=production"
